version: "3.7"

services:

  # redis
  # --------------------------------
  redis:
    image: redis:7.0.5-alpine
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_DB=0
    depends_on:
      - redis
    ports:
      - 8001:8081
    restart: unless-stopped
  # --------------------------------

  # rabbitmq
  # --------------------------------
  rabbitmq:
    image: rabbitmq:3.11.8-management-alpine
    hostname: my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - 8002:15672
      - 5672:5672
    restart: unless-stopped
  # --------------------------------

  # mongodb
  # --------------------------------
  mongodb:
    image: mongo:6.0.5-jammy
    volumes:
      - ./data/mongodb:/data/db
      - ./dev/dump:/dump
      - ./dev/load.sh:/docker-entrypoint-initdb.d/load.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8003:8081
  # --------------------------------

  # webui
  # --------------------------------
  webui:
    image: mtr.devops.telekom.de/chain-factory/webui:1.2.0
    restart: unless-stopped
    ports:
      - 8004:8000
    environment:
      - API_URL=http://localhost:8005
      - NODE_ENV=production