# -- BUILD --
FROM node:12.13.0-alpine as build

WORKDIR /usr/src/app

COPY webui/package.json ./
COPY webui/tsconfig.json ./
COPY webui/.babelrc ./
COPY webui/.gitignore ./

RUN npm install

COPY webui/src/ ./src/
COPY webui/public ./public/

RUN npm run build

COPY webui/.env.example ./
COPY webui/nginx/ ./nginx/

# -- RELEASE --
FROM nginx:stable-alpine as release

COPY --from=build /usr/src/app/build /usr/share/nginx/html
# copy .env.example as .env to the release build
COPY --from=build /usr/src/app/.env.example /usr/share/nginx/html/.env
COPY --from=build /usr/src/app/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/nginx/nginx.conf /etc/nginx/nginx.conf

RUN apk add --update nodejs
RUN apk add --update npm
RUN npm install -g runtime-env-cra@0.2.2

WORKDIR /usr/share/nginx/html

RUN chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d && \
    chown -R nginx:nginx /usr/share/nginx/html

RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

USER nginx

EXPOSE 8000

CMD ["/bin/sh", "-c", "runtime-env-cra && nginx -g \"daemon off;\""]